name: Chore/Maintenance
description: Infrastructure, refactoring, or maintenance tasks
title: "[CHORE] "
labels: ["Type: chore", "triage"]
assignees:
  - BOUTCHOUANG1
body:
  - type: markdown
    attributes:
      value: |
        Use this template for infrastructure improvements, refactoring, or maintenance tasks.

  - type: dropdown
    id: chore-type
    attributes:
      label: Type of Chore
      description: What type of maintenance task is this?
      options:
        - Infrastructure
        - Refactoring
        - Dependencies Update
        - CI/CD
        - Documentation
        - Code Quality
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be done and why
      placeholder: Provide a clear description of the maintenance task
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this chore necessary? What problem does it solve?
      placeholder: Explain the motivation behind this task
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Break down the work into specific tasks
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the application does this affect?
      options:
        - Authentication
        - Database
        - Grades Management
        - Infrastructure
        - CI/CD
        - Reports
        - General
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this chore?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How much work do you estimate this will be?
      options:
        - S - Small (1-2 days)
        - M - Medium (3-5 days)
        - L - Large (1+ weeks)
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this chore is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true