blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/BOUTCHOUANG1/University-Grade-MS/wiki
    about: Check the project documentation and wiki for guidance
  - name: 💬 Discussions
    url: https://github.com/BOUTCHOUANG1/University-Grade-MS/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/BOUTCHOUANG1/University-Grade-MS/security/advisories/new
    about: Report security vulnerabilities privately