name: ✨ Feature Request
description: Suggest a new feature for the University Grade Management System
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current pain point?
      placeholder: |
        As a [user type], I want to [goal] so that [reason].
        
        Currently, [describe the problem or limitation]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see [describe the feature]...
        
        This would work by [describe how it works]...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the specific requirements that must be met for this feature to be considered complete.
      placeholder: |
        - [ ] User can perform action X
        - [ ] System responds with Y
        - [ ] Data is validated according to Z rules
        - [ ] Error handling for edge cases A, B, C
        - [ ] Feature works on mobile and desktop
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches could include...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High (Critical for business needs)
        - Medium (Important but not urgent)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information, screenshots, or examples...
    validations:
      required: false