name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["type: feature", "P3"]
projects: ["BOUTCHOUANG1/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve or the need this feature addresses.
      placeholder: What problem does this feature solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: How should this feature work? What should it do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Have you considered any other approaches?
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what needs to be true for this feature to be considered complete.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2  
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 (Critical - needed immediately)
        - P1 (High - needed soon)
        - P2 (Medium - nice to have)
        - P3 (Low - future consideration)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the system does this feature relate to?
      options:
        - Authentication & Authorization
        - Database & Data Management
        - Grades & Academic Records
        - Infrastructure & DevOps
        - Reports & Analytics
        - User Interface
        - API & Integration
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or examples to help explain your feature request.
      placeholder: Drag and drop images here or describe the UI/UX...
    validations:
      required: false

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Any technical considerations, constraints, or implementation notes.
      placeholder: Technical details, dependencies, potential challenges...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
    validations:
      required: false