name: Feature Request
description: Suggest a new feature or enhancement for the University Grade Management System
title: "[FEATURE] "
labels: ["type:feature", "status:triage"]
projects: ["BOUTCHOUANG1/1"]
# Note: Update project number if different. To find: Projects → Backend Roadmap → Settings → Check URL
assignees:
  - BOUTCHOUANG1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A brief title for the feature
      placeholder: "Short descriptive title for the feature"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the system would this feature affect?
      options:
        - "Authentication/Authorization"
        - "Database/Data Management"
        - "Grade Management"
        - "User Interface"
        - "API/Backend"
        - "Reports/Analytics"
        - "Email/Notifications"
        - "Infrastructure/CI/CD"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - "P0 - Critical/Urgent"
        - "P1 - High priority"
        - "P2 - Medium priority"
        - "P3 - Low priority/Nice to have"
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How complex do you think this feature would be to implement?
      options:
        - "S - Small (1-2 days)"
        - "M - Medium (3-5 days)"
        - "L - Large (1+ weeks)"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: "Describe the problem or limitation this feature would address"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "Describe how you envision this feature working"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Describe any alternative solutions you've considered"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how different users would interact with this feature
      placeholder: |
        As a [user type], I want [functionality] so that [benefit/value]
        
        Example:
        - As a student, I want to view my grade trends over time so that I can track my academic progress
        - As a teacher, I want to bulk upload grades from a CSV file so that I can save time on data entry

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any mockups, wireframes, or visual examples, please include them here
      placeholder: "Attach images or describe the visual design"

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Are there any technical aspects, dependencies, or constraints to consider?
      placeholder: "Database changes, API changes, security considerations, performance impact, etc."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or examples
      placeholder: "Any additional information that would be helpful"